### ISSUE TITLE
Could gcp-gke/create-cluster be idempotent?

### ISSUE THREAD

**Issue by WillGibson** [CircleCI-Public/gcp-gke-orb#25]
### Orb version

1.0.4

### What happened

First time the pipeline runs the cluster is created.

Subsequently it errors because the cluster already exists...

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=409, message=Already exists: projects/*********************/zones/**************/clusters/*********************-cluster.
```

### Expected behaviour

Ideally, the command would be idempotent and just apply any changes if the cluster already exists.

**Comment by krtk6160** [comment]
I too would like to know if this is possible as I'm facing the same issue.

**Comment by EricRibeiro** [comment]
Hi @WillGibson and @krtk6160, thank you for making this suggestion.

As @Jaryt nicely put in #44, _infrastructure created in the pipeline is ephemeral_. This is to say that if you are using this orb to create a cluster in your pipeline, you should be deleting it by the end of the last job that needs it. Otherwise, you will fall into the anti-pattern of using your CircleCI YAML configuration to manage your infrastructure.

We want to discourage this, so we will not move forward with this implementation, but we are updating our documentation in #45 to show how the orb must be used. Feel free to review it and provide us with your feedback.
